server:
  port: 81

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dictionary?serverTimezone=UTC&Unicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    timeout: 0
    password: 1234
    database: 0

logging:
  file:
    path: logs/shiro/
    name: ${logging.file.path}shiro.log
  charset:
    console: UTF-8
  level:
    root: info
    com:
      gx: debug

mybatis-plus:
  type-aliases-package: cn.com.dictionary.dao.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperLocations: classpath:cn/com/**/*.xml